CC = i386-elf-gcc -fno-builtin

build:
	$(CC) -o dec_hex.o -c dec_hex.c
	$(CC) -o exit.o -c exit.c
	$(CC) -o jpeg.o -c jpeg.c
	$(CC) -o malloc.o -c malloc.c
	$(CC) -o math.o -c math.c
	$(CC) -o mfree.o -c mfree.c
	$(CC) -o printf.o -c printf.c
	$(CC) -o putchar.o -c putchar.c
	$(CC) -o sprintf.o -c sprintf.c
	$(CC) -o str.o -c str.c
